apiVersion: v1
kind: Pod
metadata:
  labels:
    role: build-agent
spec:
  restartPolicy: Never
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1
  containers:
    - name: android-builder
      image: mobiledevops/android-sdk-image:34.0.0
      command:
        - cat
      tty: true
      securityContext:
        runAsUser: 0
      resources:
        requests:
          cpu: "4"
          memory: "512Mi"
        limits:
          cpu: "6"
          memory: "1536Mi"
